# Generated by Django 5.1.1 on 2024-10-09 11:33

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliar_IMC',
            fields=[
                ('cpf', models.FloatField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPf')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sexo', models.CharField(max_length=15, verbose_name='Genero')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento ')),
                ('escola', models.CharField(max_length=200, verbose_name='Escola Matriculada')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='', variations={'thumb': (124, 124)}, verbose_name='Imagem do juio')),
            ],
        ),
    ]
