# Generated by Django 5.1.1 on 2024-10-09 12:14

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essencialmente_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliar_imc',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='', variations={'thumb': (124, 124)}, verbose_name='Imagem do produto'),
        ),
    ]
